server {
  listen 3000;
  server_name localhost;
  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # pass API requests to the backend container (compose will map hostnames)
  location /api/ {
    proxy_pass http://backend:8000/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /recipes/ {
    proxy_pass http://backend:8000/recipes/;
  }
}
